#!/usr/bin/env python3
"""Build study-site data for offline file:// (double-click index.html)."""
import json
import re
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent
ROOT = SITE_DIR.parent
NOTES = ROOT / "notes"
DATA_DIR = SITE_DIR / "data"
OUT_JSON = DATA_DIR / "chapters.json"
OUT_JS = DATA_DIR / "chapters.js"

CHAPTER_FILES = [
    ("overview", "课程整体要求", ROOT / "课程整体要求.md"),
    ("01", "第0–1章 绪论与工程认识", NOTES / "01-绪论与工程认识.md"),
    ("03", "第3章 系统分析", NOTES / "03-系统分析.md"),
    ("04", "第4章 工程与伦理", NOTES / "04-工程与伦理.md"),
    ("05", "第5章 工程与法律法规", NOTES / "05-工程与法律法规.md"),
    ("06", "第6–7章 标准化与可持续发展", NOTES / "06-标准化与可持续发展.md"),
    ("08", "第8章 工程经济决策基础", NOTES / "08-工程经济决策基础.md"),
    ("09", "第9–10章 工程经济决策方法", NOTES / "09-工程经济决策方法.md"),
    ("11", "第11章 项目管理概述", NOTES / "11-工程项目管理概述.md"),
    ("12", "第12章 项目启动和范围管理", NOTES / "12-项目启动与范围管理.md"),
]

IMPORTANCE = {
    "overview": "★★☆",
    "01": "★★☆",
    "03": "★★☆",
    "04": "★★★",
    "05": "★★☆",
    "06": "★★☆",
    "08": "★★★",
    "09": "★★★",
    "11": "★★☆",
    "12": "★★☆",
}

LINK_MAP = {
    "../课程整体要求.md": "#overview",
    "./课程整体要求.md": "#overview",
    "./08-工程经济决策基础.md": "#08",
    "../课程整体要求.md": "#overview",
}


def extract_meta(text: str) -> dict:
    m = re.search(r"建议复习[：:]\s*([^\n|]+)", text)
    duration = m.group(1).strip() if m else ""
    tags = []
    if "必算" in text or "★★★" in text[:800]:
        tags.append("计算")
    if "案例" in text[:1200] or "挑战者" in text:
        tags.append("案例")
    return {"duration": duration, "tags": tags}


def fix_markdown_links(md: str) -> str:
    md = re.sub(
        r"\[课程整体要求\.md\]\([^)]+\)",
        "[课程整体要求](#overview)",
        md,
    )
    md = re.sub(
        r"\[08-工程经济决策基础\.md\]\([^)]+\)",
        "[第8章](#08)",
        md,
    )
    return md


def main():
    chapters = []
    for cid, title, path in CHAPTER_FILES:
        if not path.exists():
            raise FileNotFoundError(path)
        content = fix_markdown_links(path.read_text(encoding="utf-8"))
        meta = extract_meta(content)
        chapters.append(
            {
                "id": cid,
                "title": title,
                "importance": IMPORTANCE.get(cid, "★★☆"),
                "duration": meta["duration"],
                "tags": meta["tags"],
                "markdown": content,
            }
        )

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(chapters, ensure_ascii=False, indent=2), encoding="utf-8")

    js_body = json.dumps(chapters, ensure_ascii=False)
    OUT_JS.write_text(
        "/* Auto-generated by build.py — enables double-click index.html */\n"
        "window.GONGCHENG_CHAPTERS = " + js_body + ";\n",
        encoding="utf-8",
    )
    print(f"Built {OUT_JSON} and {OUT_JS} ({len(chapters)} chapters)")


if __name__ == "__main__":
    main()
